### ISSUE TITLE
Fails to load with ruby 3.3.0

### ISSUE THREAD

**Issue by timon** [emancu/toml-rb#144]
Hey there,
this is to let you know that toml-rb 2.0.3 doesn't work with ruby 3.3:

<details>
<summary>~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/tomlrb-2.0.3/lib/tomlrb
/generated_parser.rb:7:in `require': cannot load such file -- racc/parser.rb (LoadError)</summary>

```
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/tomlrb-2.0.3/lib/tomlrb/generated_parser.rb:7:in `<top (required)>'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/tomlrb-2.0.3/lib/tomlrb/parser.rb:1:in `require'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/tomlrb-2.0.3/lib/tomlrb/parser.rb:1:in `<top (required)>'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/tomlrb-2.0.3/lib/tomlrb.rb:9:in `require'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/tomlrb-2.0.3/lib/tomlrb.rb:9:in `<top (required)>'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/license_finder-7.1.0/lib/license_finder/package_managers/dep.rb:3:in `require'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/license_finder-7.1.0/lib/license_finder/package_managers/dep.rb:3:in `<top (required)>'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/license_finder-7.1.0/lib/license_finder/package_manager.rb:175:in `require'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/license_finder-7.1.0/lib/license_finder/package_manager.rb:175:in `<top (required)>'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:9:in `require'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:9:in `<top (required)>'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/license_finder-7.1.0/lib/license_finder.rb:13:in `require'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/license_finder-7.1.0/lib/license_finder.rb:13:in `<top (required)>'
	from bin/myapp:4:in `require'
	from bin/myapp:4:in `<top (required)>'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/cli/exec.rb:58:in `load'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/cli/exec.rb:23:in `run'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/cli.rb:485:in `exec'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/cli.rb:31:in `dispatch'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/cli.rb:25:in `start'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/exe/bundle:48:in `block in <top (required)>'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from ~/Sources/myapp/vendor/bundle/ruby/3.3.0/gems/bundler-2.3.21/exe/bundle:36:in `<top (required)>'
	from ~/.rbenv/versions/3.3.0/bin/bundle:25:in `load'
	from ~/.rbenv/versions/3.3.0/bin/bundle:25:in `<main>'
</details>

**Comment by timon** [comment]
Created PR #145 to address the issue
