### ISSUE TITLE
Issue with Rubinius

### ISSUE THREAD

**Issue by bararchy** [emancu/toml-rb#54]
When using Rubinius to run a script that uses toml-rb I get this issue:
![selection_002](https://cloud.githubusercontent.com/assets/1631073/6248482/bf38a5be-b788-11e4-862b-32cef6c3c02e.png)
When using Ruby MRI 2.2.0 I don't get any issues, so... I'm not sure how to continue from here.

**Comment by emancu** [comment]
@bararchy well, I didn't add support for `rubinius` yet.

Actually I'm not sure if `citrus` works well with `rubinius` so I have to do some tests for that library too.
Could you tell me which version of rubinius are you using?

I'll take a look later, I'm currently working on specs for `0.4.0`

**Comment by bararchy** [comment]
@emancu  Thanks :) 

Right now I'm using ```rubinius 2.5.2.c80 (2.1.0 4417909e 2015-02-17 3.5.1 JI) [x86_64-linux-gnu]```
Which is the RVM version ```rbx-head```
The gems compile and installs as they should, maybe Rubinius does something to the toml-rb source or something...  I'll be more then happy to provide code pieces, gem files , etc... to help.

**Comment by emancu** [comment]
@bararchy it seems like `citrus` doesn't support _rubinius_ :disappointed: 

So I can't fix it since `citrus` is a dependency.

**Comment by bararchy** [comment]
@emancu , I opened an issue with citrus, they have now fixed compatibility with rubinius, would you reconsider ? 

https://github.com/mjackson/citrus/issues/51

**Comment by emancu** [comment]
I just run all the `toml` tests with the latest rubinius

```bash
master]@toml-rb$ rake
Run options:

# Running tests:

Finished tests in 0.660443s, 45.4241 tests/s, 143.8428 assertions/s.
30 tests, 95 assertions, 0 failures, 0 errors, 0 skips

ruby -v: rubinius 2.5.2.c83 (2.1.0 b887ca9a 2015-02-20 3.5.1 JI) [x86_64-darwin14.1.0]
```
Could you confirm if this is still an issue ?

**Comment by bararchy** [comment]
Using irb:
```
rbx-head :001 > require 'toml'
Citrus::SyntaxError: /home/unshadow/.rvm/gems/rbx-head/gems/toml-rb-0.3.0/lib/toml/grammars/helper.citrus: Malformed Citrus syntax on line 3 at offset 10
    (space? "#" (~line_break)* line_break?) { nil }

          ^
	from /home/unshadow/.rvm/gems/rbx-head/gems/citrus-3.0.2/lib/citrus/file.rb:361:in `parse'
	from /home/unshadow/.rvm/gems/rbx-head/gems/citrus-3.0.2/lib/citrus.rb:47:in `eval'
	from /home/unshadow/.rvm/gems/rbx-head/gems/citrus-3.0.2/lib/citrus.rb:77:in `load'
	from /home/unshadow/.rvm/gems/rbx-head/gems/toml-rb-0.3.0/init.rb:13:in `__script__'
	from kernel/common/code_loader.rb:247:in `require'
	from kernel/common/code_loader.rb:147:in `require_relative'
	from kernel/common/kernel.rb:762:in `require_relative'
	from /home/unshadow/.rvm/gems/rbx-head/gems/toml-rb-0.3.0/lib/toml.rb:1:in `__script__'
	from kernel/common/code_loader.rb:247:in `require'
	from kernel/common/kernel.rb:756:in `gem_original_require (require)'
	from /home/unshadow/.rvm/rubies/rbx-head/site/rubygems/core_ext/kernel_require.rb:128:in `require'
	from (irb):1
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from kernel/common/kernel.rb:511:in `loop'
	from kernel/bootstrap/proc.rb:20:in `call'
... 1 levels...
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from /home/unshadow/.rvm/gems/rbx-head@global/gems/rubysl-irb-2.1.1/bin/irb:12:in `__script__'
	from kernel/common/kernel.rb:498:in `load'
	from /home/unshadow/.rvm/gems/rbx-head@global/bin/irb:23:in `__script__'
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from /home/unshadow/.rvm/gems/rbx-head/bin/ruby_executable_hooks:15:in `__script__'
	from kernel/delta/code_loader.rb:66:in `load_script'
	from kernel/delta/code_loader.rb:152:in `load_script'
	from kernel/loader.rb:656:in `script'
	from kernel/loader.rb:810:in `main'rbx-head 
``` 

Or Rake:
```
┌─( unshadow ) - ( ~/Desktop/git-projects/toml-rb )
└──┤ rake
rake aborted!
Citrus::SyntaxError: /home/unshadow/Desktop/git-projects/toml-rb/lib/toml/grammars/helper.citrus: Malformed Citrus syntax on line 3 at offset 10
    (space? "#" (~line_break)* line_break?) { nil }

          ^/home/unshadow/.rvm/gems/rbx-head/gems/citrus-3.0.2/lib/citrus/file.rb:361:in `parse'
/home/unshadow/.rvm/gems/rbx-head/gems/citrus-3.0.2/lib/citrus.rb:47:in `eval'
/home/unshadow/.rvm/gems/rbx-head/gems/citrus-3.0.2/lib/citrus.rb:77:in `load'
/home/unshadow/Desktop/git-projects/toml-rb/init.rb:13:in `__script__'
kernel/common/code_loader.rb:247:in `require'
kernel/common/code_loader.rb:147:in `require_relative'
kernel/common/kernel.rb:762:in `require_relative'
/home/unshadow/Desktop/git-projects/toml-rb/lib/toml.rb:1:in `__script__'
kernel/common/code_loader.rb:247:in `require'
kernel/common/code_loader.rb:147:in `require_relative'
kernel/common/kernel.rb:762:in `require_relative'
/home/unshadow/Desktop/git-projects/toml-rb/test/helper.rb:2:in `__script__'
kernel/common/code_loader.rb:247:in `require'
kernel/common/code_loader.rb:147:in `require_relative'
kernel/common/kernel.rb:762:in `require_relative'
/home/unshadow/Desktop/git-projects/toml-rb/test/errors_test.rb:1:in `__script__'
kernel/common/kernel.rb:498:in `load'
/home/unshadow/Desktop/git-projects/toml-rb/Rakefile:2:in `__script__'
kernel/bootstrap/array.rb:76:in `each'
/home/unshadow/Desktop/git-projects/toml-rb/Rakefile:2:in `__script__'
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/array.rb:76:in `each'
/home/unshadow/.rvm/rubies/rbx-head/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
kernel/bootstrap/array.rb:76:in `each'
/home/unshadow/.rvm/rubies/rbx-head/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
kernel/bootstrap/array.rb:76:in `each'
kernel/common/kernel.rb:498:in `load'
kernel/common/block_environment.rb:53:in `call_on_instance'
kernel/common/eval.rb:176:in `eval'
/home/unshadow/.rvm/gems/rbx-head/bin/ruby_executable_hooks:15:in `__script__'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:656:in `script'
kernel/loader.rb:810:in `main'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

This is while using latest toml-rb: 

```
┌─( unshadow ) - ( ~/Desktop/git-projects )
└──┤ git clone https://github.com/emancu/toml-rb.git
Cloning into 'toml-rb'...
remote: Counting objects: 912, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 912 (delta 21), reused 0 (delta 0)
Receiving objects: 100% (912/912), 124.42 KiB | 86.00 KiB/s, done.
Resolving deltas: 100% (475/475), done.
Checking connectivity... done.
┌─( unshadow ) - ( ~/Desktop/git-projects )
└──┤ cd toml-rb/
┌─( unshadow ) - ( ~/Desktop/git-projects/toml-rb )
└──┤ ls
init.rb  lib  Rakefile  README.md  test  toml-rb.gemspec
┌─( unshadow ) - ( ~/Desktop/git-projects/toml-rb )
└──┤ gem build toml-rb.gemspec 
  Successfully built RubyGem
  Name: toml-rb
  Version: 0.3.0
  File: toml-rb-0.3.0.gem
┌─( unshadow ) - ( ~/Desktop/git-projects/toml-rb )
└──┤ gem install toml-rb
toml-rb-0.3.0.gem  toml-rb.gemspec    
┌─( unshadow ) - ( ~/Desktop/git-projects/toml-rb )
└──┤ gem install toml-rb-0.3.0.gem 
Successfully installed toml-rb-0.3.0
Parsing documentation for toml-rb-0.3.0
Done installing documentation for toml-rb after 1 seconds
1 gem installed
```

Version:
```
 ruby -v
rubinius 2.5.2.c80 (2.1.0 4417909e 2015-02-17 3.5.1 JI) [x86_64-linux-gnu]

```

**Comment by emancu** [comment]
@bararchy it was fixed yesterday on rubinius so you should update it to version `2.5.2.c83`

**Comment by bararchy** [comment]
It's working with latest Rubinius ! thanks :) 

```
└──┤ rvm use rbx-head
Using /home/unshadow/.rvm/gems/rbx-head
┌─( unshadow ) - ( ~ )
└──┤ gem update
Updating installed gems
Nothing to update
┌─( unshadow ) - ( ~ )
└──┤ pry
[1] pry(main)> require 'toml'
=> true
[2] pry(main)> 

```
